### ISSUE TITLE
Missing Page or wrong link: Getting started -> Mod user ->  set up the Godot ModLoader

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/gmlwiki#7]
On [Getting Started - Mod user](https://wiki.godotmodding.com/#/README?id=mod-user) [set up the Godot ModLoader](https://wiki.godotmodding.com/#/guides/integration/godot_project_setup) links to `godot_project_setup` instead of https://github.com/GodotModding/godot-mod-loader/wiki/Mod-Loader-Self-Setup

**Comment by ZackeryRSmith** [comment]
Whoops, this slipped by me. I will fix this on the [MkDocs](https://github.com/GodotModding/gmlwiki/tree/mkdocs) branch as soon Docsify is going to be left in the dust
